### ISSUE TITLE
Cancel button is not available on Add and Edit category page. 

### ISSUE THREAD

**Issue by prasoonravindran** [renjithprince/Project-Architecture#10]
Cancel button is not available on Add and Edit category page.  Only submit is displaying.  So there is no option to go back to the previous page.  

![cancel button](https://cloud.githubusercontent.com/assets/5270017/20617561/15eaa28e-b310-11e6-8ddd-2cdc10534f61.jpg)

![cancel button2](https://cloud.githubusercontent.com/assets/5270017/20617566/1f283492-b310-11e6-9227-4fb318f7d552.jpg)

**Comment by ashireader** [comment]
completed
