### ISSUE TITLE
Invalid file get uploaded as cover image. 

### ISSUE THREAD

**Issue by prasoonravindran** [renjithprince/Project-Architecture#3]
Invalid file get uploaded as cover image.  Try to upload file format other than image,  The file got uploaded, Not displayed any Validation. 
![invalid](https://cloud.githubusercontent.com/assets/5270017/20473092/3a4013dc-afe4-11e6-8724-dcb1824a9f28.jpg)

**Comment by ashireader** [comment]
fixed
