### ISSUE TITLE
Exception after clicking on Edit project status button.  

### ISSUE THREAD

**Issue by prasoonravindran** [renjithprince/Project-Architecture#7]
Exception after clicking on Edit project status button from manage project page.   

![status 1](https://cloud.githubusercontent.com/assets/5270017/20617345/866dafe4-b30e-11e6-9280-c43ceaa93ab3.jpg)
![status 2](https://cloud.githubusercontent.com/assets/5270017/20617356/90f81c56-b30e-11e6-91e9-1567062ba3bf.jpg)

**Comment by ashireader** [comment]
Fixed
